### PR TITLE
Task 1 done

### PR DESCRIPTION
**Pull request by kartiksharma1227**
Issue: #1 
Dataset has been loaded and modified as mentioned.
Code added to display one image of all the 22 classes.

image

### CODE REVIEW

**Comment by saumyacoder1709** [comment]
Add just one .ipynb file

**Comment by kartiksharma1227** [comment]
> Add just one .ipynb file

Yes I have added only one file named IIT2023143.ipynb.

**Comment by saumyacoder1709** [comment]
You are adding a file named .DS_Store

**Comment by kartiksharma1227** [comment]
> You are adding a file named .DS_Store

I am sorry , I don't see that file could you please be specific where is that located?

**Comment by saumyacoder1709** [comment]
You are actually pushing two files. Try forking the repo again and then pushing the .ipynb file only. Make a new PR for the same.

**Comment by kartiksharma1227** [comment]
Alright thanks.

**Pull request closed without merging**
